name: '01 - Execução por push'

on:
  push:
    branches: [main]

jobs:
  execucao-pipeline_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      - run: npm test
        continue-on-error: true

      - name: Install Mocha
        run: npm install mocha
        continue-on-error: true

      - name: Gerar relatório JSON com Mocha
        run: npx mocha --reporter json --reporter-option output=test-results.json
        continue-on-error: true

      - uses: dorny/test-reporter@v2
        name: Publicar relatório
        if: always()
        with:
          artifact: test-results
          name: Mocha Tests
          path: test-results.json
          reporter: mocha-json
