name: Execução por push

on:
  push:
    branches: [main]


jobs:
  execucao-teste:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm

      - name: Instalando dependencias
        run: |
          npm ci

      - name: Executar os testes e gerar o report
        run: npx allure run -- npm run test

      - name: Allure Report Official
        uses: allure-framework/allure-action@v0
        with:
          report-directory: "./"
          remote-href: "https://allure-framework.github.io/allure-action/"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar relatório de testes
        if: always()
        uses: allure-framework/allure-action@v0
        with:
          report-directory: "./allure-report"

            