name: Execução por push

on:
  push:
    branches: [main]


jobs:
  execucao-teste:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm

      - name: Instalando dependencias
        run: |
          npm ci

      - name: Instalar Mochawesome
        run: npm install --save-dev mocha-junit-reporter

      - name: Execução dos testes e relatório com Mochawesome visualização XML
        run: npx mocha test/servicospagamento.test.js --reporter mochawesome --reporter-options reportDir=mochawesome-report

      - name: Publicar relatório de testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio_testes
          path: ./

            