name: '02 - Execução manual'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 16,21 * * 5'


jobs:
  execucao-pipeline_manual:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - run: npm ci

      - run: npm test
        continue-on-error: true

      - name: Install Mocha
        run: npm install mocha
        continue-on-error: true

      - name: Gerar relatório JSON com Mocha
        run: npx mocha --reporter json --reporter-option output=relatorio-testes.json
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-testes
          path: relatorio-testes.json

      - name: Publicar relatório
        uses: dorny/test-reporter@v2
        if: always()
        with:
          artifact: test-results
          name: Relatorio de Testes com o Mocha
          path: relatorio-testes.json
          reporter: mocha-json