name: 'Execução da pipeline'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 16,21 * * 5'

jobs:
  execucao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - run: npm ci

      - run: npm test
        continue-on-error: true

      - name: Install Mocha
        run: npm install mocha
        continue-on-error: true

      - name: Executar testes e gerar relatório
        run: npx mocha --reporter json --reporter-option output=test-results.json
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        if: always()
        continue-on-error: true
        with:
          name: test-results
          path: test-results.json

      - name: Publicar relatório
        uses: dorny/test-reporter@v3
        if: always()
        continue-on-error: true
        with:
          artifact: test-results
          name: Mocha Tests
          path: 'test-results.json'
          reporter: mocha-json